### ISSUE TITLE
Mockups or other design artifacts

### ISSUE THREAD

**Issue by stevenmusumeche** [stevenmusumeche/asg-website#7]
This will enable the UI to be built, so should include colors, fonts, etc.

**Comment by arthyn** [comment]
## Mockup
https://www.figma.com/file/VVYVD1zru5oz5PI7MtMhyM/ASG-Site-public

The link above is a public draft of the mockup that anyone can edit or play around with. I keep a private version just to retain the original. You should be able to inspect to get any necessary values. But for quick reference:

## Fonts
*[ITC Avant Garde Gothic Pro](https://fonts.adobe.com/fonts/itc-avant-garde-gothic)* - Medium & Bold
*[Sofia Pro](https://fonts.adobe.com/fonts/sofia)* - Regular, Italic & Bold

These fonts are contained in this typekit:
```
<link rel="stylesheet" href="https://use.typekit.net/pex4ebf.css">
```

## Colors
`#0E1EB3` used as a background and also text color when on white background
`#B50F0F` used as an accent in combination with yellow
`#EFBF17` used as an accent in combination with red

## Mockup Preview
![image](https://user-images.githubusercontent.com/5466421/53342073-c91e3b00-38d2-11e9-8ed5-0af4c321dda5.png)

**Comment by stevenmusumeche** [comment]
I love the colors and the mockup preview.  A few comments:

1. I'm not sure how we can actually implement the "decoration" in a way that works with dynamic content. Will it be possible?
2. Are Adobe fonts free to use? How might they affect performance?
